version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: test
        linters:
          - staticcheck
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
