apiVersion: databases.qfzack.com/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: k8s-crd-demo
    app.kubernetes.io/managed-by: kustomize
  name: redis-instance
spec:
  name: redis
  image: bitnami/redis:7.0.0
  replicas: 3
  mode: standalone
  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  storage:
    accessMode: ReadWriteOnce
    storage: 1Gi
    storageClassName: thin-csi
  config:
    # ALLOW_EMPTY_PASSWORD: true
    REDIS_PASSWORD: "Password!"  # TODO set password with secrets
  # monitor:
  backup:
    enabled: true
    schedule: "0 0 * * *"
    # retention: 7
    # retentionPolicy:
  security:
    enableTLS: false
