apiVersion: databases.qfzack.com/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: k8s-crd-demo
    app.kubernetes.io/managed-by: kustomize
  name: redis-instance
spec:
  name: redis-server
  port: 6379
  replicas: 3
