name: Build and Push Helm Chart

on:
  push:
    tags:
      - '*'
    branches:
      - redis-operator

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Install helmify
      run: |
        curl -LO https://github.com/arttor/helmify/releases/latest/download/helmify_Linux_x86_64.tar.gz
        tar -zxvf helmify_Linux_x86_64.tar.gz
        chmod +x helmify
        sudo mv helmify /usr/local/bin/

    - name: Set up Helm
      uses: azure/setup-helm@v3

    # - name: Build Helm chart
    #   run: |
    #     kustomize build config/default | helmify charts/redis-operator

    - name: Configure Git
      run: |
        git config user.name "qingfeng_zhang"
        git config user.email "zhangqf829@gmail.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: charts
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
